"""
display.py

nanoMon display preparation layer.

Purpose:
    Convert raw Docker statistics collected by statistics.py
    into data structures suitable for HTML rendering.

This module does not:
    - collect Docker data
    - create HTML
    - manage containers

It only prepares presentation data.
"""

from typing import Any


class DockerDisplay:
    """
    Formats Docker statistics for display.

    Input:
        Raw dictionary generated by DockerStatistics.collect_all()

    Output:
        Display-ready dictionary for templates.
    """


    def __init__(
        self,
        docker_data: dict[str, Any]
    ):
        """
        Initialize display processor.

        Args:
            docker_data:
                Dictionary containing Docker statistics.

        Raises:
            TypeError:
                If docker_data is not a dictionary.
        """

        if not isinstance(
            docker_data,
            dict
        ):
            raise TypeError(
                "Docker data must be a dictionary."
            )

        self.docker_data = docker_data


    def create_summary_cards(
        self
    ) -> list[dict[str, str]]:
        """
        Create summary card information.

        Returns:
            List of summary card dictionaries.
        """

        summary = self.docker_data.get(
            "summary",
            {}
        )

        return [
            {
                "title": "Containers",
                "value": str(
                    summary.get(
                        "total_containers",
                        0
                    )
                ),
                "style": "primary"
            },
            {
                "title": "Running",
                "value": str(
                    summary.get(
                        "running_containers",
                        0
                    )
                ),
                "style": "success"
            },
            {
                "title": "Stopped",
                "value": str(
                    summary.get(
                        "stopped_containers",
                        0
                    )
                ),
                "style": "secondary"
            }
        ]


    def create_running_table(
        self
    ) -> list[dict[str, str]]:
        """
        Format running containers.

        Returns:
            List of running container rows.
        """

        results = []

        for container in self.docker_data.get(
            "running",
            []
        ):

            results.append(
                {
                    "name": container.get(
                        "name",
                        "unknown"
                    ),
                    "status": "Running",
                    "cpu": (
                        f"{container.get('cpu_percent', 0)}%"
                    ),
                    "memory": (
                        f"{container.get('memory_used_mib', 0)} MB"
                    ),
                    "restart": container.get(
                        "restart_policy",
                        "unknown"
                    ),
                    "uptime": container.get(
                        "uptime",
                        "unknown"
                    )
                }
            )

        return results


    def create_stopped_table(
        self
    ) -> list[dict[str, str]]:
        """
        Format stopped containers.

        Returns:
            List of stopped container rows.
        """

        results = []

        for container in self.docker_data.get(
            "stopped",
            []
        ):

            results.append(
                {
                    "name": container.get(
                        "name",
                        "unknown"
                    ),
                    "status": container.get(
                        "status",
                        "unknown"
                    ),
                    "reason": container.get(
                        "reason",
                        "unknown"
                    ),
                    "restart": container.get(
                        "restart_policy",
                        "unknown"
                    )
                }
            )

        return results


    def prepare(
        self
    ) -> dict[str, Any]:
        """
        Prepare complete display data.

        Returns:
            Dictionary ready for HTML templates.
        """

        return {
            "timestamp": self.docker_data.get(
                "timestamp",
                ""
            ),
            "summary_cards": self.create_summary_cards(),
            "running_containers": self.create_running_table(),
            "stopped_containers": self.create_stopped_table()
        }


if __name__ == "__main__":
    """
    Production Data
    """
    from statistics import DockerStatistics
    docker_statistics = DockerStatistics()
    test_data = docker_statistics.collect_all()

    display = DockerDisplay(
        test_data
    )

    result = display.prepare()

    print(result)